import { ToastContainer } from 'react-toastify'
import './globals.css'
import GlobalThemeWrapper from './lib/GlobalThemeWrapper'
import StyledComponentsRegistry from './lib/register'
import 'react-toastify/dist/ReactToastify.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalThemeWrapper>
          {children}
          
          </GlobalThemeWrapper>
        </StyledComponentsRegistry>
        <ToastContainer 
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />
      </body>
    </html>
  )
}
